### ISSUE TITLE
Assignment 1 ready for grading!

### ISSUE THREAD

**Issue by amurulid** [SES-5215-F2020/amurulidhar-quant#1]
rmd, html and csv files are all complete

**Comment by saratepfer** [comment]
Thank you, Arnav! Nice job.
**Comments on Code**
Line 37 might be a little cleaner if split into two separate mutations, where you first convert PUMA to numeric, and second perform the filter. Then you don't need to convert to numeric twice.

**Comments on Content**
You certainly don't have to do this, as you are working with enough variables in your dataset, but in addition to the variables you've selected, it may be interesting to add a categorical variable that describes whether the person rents or owns their housing.
