### ISSUE TITLE
Assignment 2 completed!

### ISSUE THREAD

**Issue by amurulid** [SES-5215-F2020/amurulidhar-quant#2]

**Comment by saratepfer** [comment]
Nice job, Arnav! Please see a few comments below:

**Comments on Code**
line 102-103: if you would like to remove scientific notation from your plot, you can insert the following line of code: options(scipen = 999)
lines 107 and 120: If you would like to save yourself a few keystrokes, these lines can be simplified to the following code: breaks = seq(0, 1000000, by = 100000))

**Comments on Content**
- I only see code/output for one of your categorical variables (BLD). Please add a table for your other categorical variable. 
- It would be helpful if you named your variable something more representative of what that variable actually is. (For example, BLD is currently "majority_race".) This would make the table clearer.
- Similarly, please make sure your captions are describing what you are showing. For example, your first table's caption describes census tracts in LA county, which is not what that table is about.

**Comment by amurulid** [comment]
@saratepfer Thanks for the feedback Sara, made the changes you suggested. (Though I decided to end up keeping the scientific notation, I find it easier to read)
