### ISSUE TITLE
Assignment 3 completed

### ISSUE THREAD

**Issue by amurulid** [SES-5215-F2020/amurulidhar-quant#3]

**Comment by saratepfer** [comment]
Nice job, Arnav! Please see a few comments below.

- If you would like to remove the scientific notation from your graphs, insert the following line of code before the ggplot() lines: options(scipen = 999)
- It would be great to see interpretation along with your anova and Tukey HSD tests.
- Same with Chi square test.
- Regarding presentation: I see that you've labeled each R chunk to indicate which test is being run. That's great and helps make your code easier to read. It would be helpful if you included similar headers/titles in your knitted html file to help the reader better understand what each of the tests is testing.
