### ISSUE TITLE
Assignment 5 completed

### ISSUE THREAD

**Issue by amurulid** [SES-5215-F2020/amurulidhar-quant#5]
https://ses-5215-f2020.github.io/amurulidhar-quant/Assignment-5.html

Thank you

**Comment by saratepfer** [comment]
Nice job, Arnav. It would be great to see more interpretation of each of your models individually, including discussion of each model's model fit. This would provide a rationale for you to choose which model is your preferred model, which isn't currently clear. It would also be nice to supplement your current work with some visualizations of the interactions you test.
